version: '3.2'
services:

    node:
        container_name: concessionaire
        image: "node:14.17-buster"
        restart: always
        user: node
        volumes:
            - ./:/var/www/html/
        working_dir: /var/www/html
        ports:
            #docker execution port
            - "3009:3009"
            #docker debbug port
            - "9662:9662"
        command: sh -c "npm install && npm run start:local && npm run typeorm:local migration:run"
        networks:
            - procontacto-net       
networks:
  procontacto-net:
    external:
        name: procontacto-network